/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity/users/{userId}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetUserEnabledRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity/users/{userId}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity/users/{userId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity/users/{userId}/roles/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignRolesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permission/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    role: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permission/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permission/roles/{role}/grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    role: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GrantPermissionsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WriteAuditRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 未认证或令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 无权限访问 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
                /** @description 系统内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: unknown;
                            errorCode?: string | null;
                            message?: string | null;
                            traceId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssignRolesRequest: {
            roles?: string[] | null;
        };
        CreateRoleRequest: {
            roleCode?: string | null;
            roleName?: string | null;
        };
        CreateUserRequest: {
            username?: string | null;
            displayName?: string | null;
            password?: string | null;
        };
        GrantPermissionsRequest: {
            permissions?: string[] | null;
        };
        LoginRequest: {
            username?: string | null;
            password?: string | null;
        };
        RefreshRequest: {
            refreshToken?: string | null;
        };
        ResetPasswordRequest: {
            newPassword?: string | null;
        };
        SetUserEnabledRequest: {
            enabled?: boolean;
        };
        WriteAuditRequest: {
            eventCode?: string | null;
            description?: string | null;
            actor?: string | null;
            level?: string | null;
            requestPath?: string | null;
            httpMethod?: string | null;
            /** Format: int32 */
            statusCode?: number | null;
            traceId?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
