// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.Infrastructure.Persistence;

#nullable disable

namespace Platform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417042735_AddAuditEventIndexes")]
    partial class AddAuditEventIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.AuditEntityChangeEntity", b =>
                {
                    b.Property<Guid>("AuditEntityChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("实体变更审计标识");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("操作人");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("变更内容JSON");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("实体标识");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("实体名称");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("发生时间");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.HasKey("AuditEntityChangeId");

                    b.HasIndex("TenantId", "EntityName", "EntityId", "OccurredAt");

                    b.ToTable("AuditEntityChanges", t =>
                        {
                            t.HasComment("实体变更审计表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("审计事件标识");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("操作人");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("描述");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("事件编码");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasComment("请求方法");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("级别");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("发生时间");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("请求路径");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasComment("状态码");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("链路追踪标识");

                    b.HasKey("AuditEventId");

                    b.HasIndex("TenantId", "EventCode");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.ToTable("AuditEvents", t =>
                        {
                            t.HasComment("审计事件表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.AuditExportJobEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("任务标识");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasComment("是否完成");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("完成时间");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("创建人");

                    b.Property<string>("CsvContent")
                        .HasColumnType("text")
                        .HasComment("CSV内容");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("错误信息");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("状态");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.HasKey("JobId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TenantId", "CreatedBy");

                    b.ToTable("AuditExportJobs", t =>
                        {
                            t.HasComment("审计导出任务表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.DictionaryItemEntity", b =>
                {
                    b.Property<Guid>("DictionaryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("字典项标识");

                    b.Property<string>("DictionaryCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("字典编码");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasComment("是否启用");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("项编码");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("项名称");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasComment("排序值");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新时间");

                    b.HasKey("DictionaryItemId");

                    b.HasIndex("TenantId", "DictionaryCode", "ItemCode")
                        .IsUnique();

                    b.HasIndex("TenantId", "DictionaryCode", "Sort");

                    b.ToTable("DictionaryItems", t =>
                        {
                            t.HasComment("字典项表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.ExternalIdentityLinkEntity", b =>
                {
                    b.Property<Guid>("ExternalIdentityLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("外部身份绑定标识");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("外部用户标识");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("绑定时间");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("提供方");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("用户标识");

                    b.HasKey("ExternalIdentityLinkId");

                    b.HasIndex("TenantId", "Provider", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("ExternalIdentityLinks", t =>
                        {
                            t.HasComment("外部身份绑定表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.NotificationMessageEntity", b =>
                {
                    b.Property<Guid>("NotificationMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("通知消息标识");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("渠道");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("内容");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("错误信息");

                    b.Property<string>("Receiver")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("接收方");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasComment("重试次数");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("发送时间");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("状态");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("标题");

                    b.HasKey("NotificationMessageId");

                    b.HasIndex("TenantId", "Status", "CreatedAt");

                    b.ToTable("NotificationMessages", t =>
                        {
                            t.HasComment("通知消息表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.NotificationTemplateEntity", b =>
                {
                    b.Property<Guid>("NotificationTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("通知模板标识");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer")
                        .HasComment("当前版本");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasComment("是否启用");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("模板编码");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("UpdatedBy字段");

                    b.HasKey("NotificationTemplateId");

                    b.HasIndex("TenantId", "TemplateCode")
                        .IsUnique();

                    b.ToTable("NotificationTemplates", t =>
                        {
                            t.HasComment("通知模板表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.NotificationTemplateVersionEntity", b =>
                {
                    b.Property<Guid>("NotificationTemplateVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("通知模板版本标识");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("变更时间");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("变更人");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasComment("内容");

                    b.Property<Guid>("NotificationTemplateId")
                        .HasColumnType("uuid")
                        .HasComment("通知模板标识");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("模板编码");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("标题");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasComment("版本号");

                    b.HasKey("NotificationTemplateVersionId");

                    b.HasIndex("NotificationTemplateId", "Version")
                        .IsUnique();

                    b.HasIndex("TenantId", "TemplateCode", "Version")
                        .IsUnique();

                    b.ToTable("NotificationTemplateVersions", t =>
                        {
                            t.HasComment("通知模板版本表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("刷新令牌标识");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("过期时间");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasComment("是否已撤销");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("令牌值");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("用户标识");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens", t =>
                        {
                            t.HasComment("刷新令牌表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.RoleDataScopeEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("角色标识");

                    b.Property<string>("CustomExpression")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("自定义表达式");

                    b.Property<int>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("修订号");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("范围");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新时间");

                    b.HasKey("RoleId");

                    b.ToTable("RoleDataScopes", t =>
                        {
                            t.HasComment("角色数据范围表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.RoleDataScopeHistoryEntity", b =>
                {
                    b.Property<Guid>("RoleDataScopeHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("角色数据范围历史标识");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("变更时间");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("变更人");

                    b.Property<string>("CustomExpression")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("自定义表达式");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasComment("角色标识");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("范围");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasComment("版本号");

                    b.HasKey("RoleDataScopeHistoryId");

                    b.HasIndex("RoleId", "Version")
                        .IsUnique();

                    b.ToTable("RoleDataScopeHistories", t =>
                        {
                            t.HasComment("角色数据范围历史表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("角色标识");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("角色编码");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("角色名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.HasKey("RoleId");

                    b.HasIndex("TenantId", "RoleCode")
                        .IsUnique();

                    b.ToTable("Roles", t =>
                        {
                            t.HasComment("角色表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasComment("角色标识");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("text")
                        .HasComment("权限编码");

                    b.HasKey("RoleId", "PermissionCode");

                    b.ToTable("RolePermissions", t =>
                        {
                            t.HasComment("角色权限关联表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.ScheduledJobEntity", b =>
                {
                    b.Property<Guid>("ScheduledJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("调度任务标识");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("错误信息");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("完成时间");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("任务类型");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasComment("最大重试次数");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("负载数据");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasComment("重试次数");

                    b.Property<DateTimeOffset>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("计划执行时间");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("状态");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.HasKey("ScheduledJobId");

                    b.HasIndex("Status", "RunAt");

                    b.ToTable("ScheduledJobs", t =>
                        {
                            t.HasComment("调度任务表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.StoredFileObjectEntity", b =>
                {
                    b.Property<Guid>("StoredFileObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("文件对象标识");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("存储桶");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("内容类型");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("文件业务标识");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("文件名");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasComment("文件大小");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("对象键");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("提供方");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("入库时间");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.HasKey("StoredFileObjectId");

                    b.HasIndex("TenantId", "FileId")
                        .IsUnique();

                    b.ToTable("StoredFileObjects", t =>
                        {
                            t.HasComment("文件存储对象表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.TenantEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasComment("是否启用");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("租户名称");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants", t =>
                        {
                            t.HasComment("租户表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.TenantSettingEntity", b =>
                {
                    b.Property<Guid>("TenantSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("租户配置标识");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("配置键");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasComment("配置值");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新时间");

                    b.HasKey("TenantSettingId");

                    b.HasIndex("TenantId", "SettingKey")
                        .IsUnique();

                    b.ToTable("TenantSettings", t =>
                        {
                            t.HasComment("租户配置表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("用户标识");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("部门编码");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("显示名称");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasComment("是否启用");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("密码哈希");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("租户标识");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("用户名");

                    b.HasKey("UserId");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasComment("用户表");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("用户标识");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasComment("角色标识");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles", t =>
                        {
                            t.HasComment("用户角色关联表");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
